/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWalletRouteImport } from './routes/_authenticated/wallet'
import { Route as AuthenticatedVehiclesRouteImport } from './routes/_authenticated/vehicles'
import { Route as AuthenticatedSavedRouteImport } from './routes/_authenticated/saved'
import { Route as AuthenticatedReservationsRouteImport } from './routes/_authenticated/reservations'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedMySlotsRouteImport } from './routes/_authenticated/my-slots'
import { Route as AuthenticatedMapRouteImport } from './routes/_authenticated/map'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedHelpRouteImport } from './routes/_authenticated/help'
import { Route as AuthenticatedEarningsRouteImport } from './routes/_authenticated/earnings'
import { Route as AuthenticatedBookingsRouteImport } from './routes/_authenticated/bookings'
import { Route as AuthenticatedAddSlotRouteImport } from './routes/_authenticated/add-slot'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedSlotIdRouteImport } from './routes/_authenticated/slot.$id'
import { Route as AuthenticatedMessagesReservationIdRouteImport } from './routes/_authenticated/messages.$reservationId'
import { Route as AuthenticatedEditSlotIdRouteImport } from './routes/_authenticated/edit-slot.$id'
import { Route as AuthenticatedAvailabilityIdRouteImport } from './routes/_authenticated/availability.$id'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWalletRoute = AuthenticatedWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVehiclesRoute = AuthenticatedVehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSavedRoute = AuthenticatedSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReservationsRoute =
  AuthenticatedReservationsRouteImport.update({
    id: '/reservations',
    path: '/reservations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMySlotsRoute = AuthenticatedMySlotsRouteImport.update({
  id: '/my-slots',
  path: '/my-slots',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMapRoute = AuthenticatedMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHelpRoute = AuthenticatedHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEarningsRoute = AuthenticatedEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBookingsRoute = AuthenticatedBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAddSlotRoute = AuthenticatedAddSlotRouteImport.update({
  id: '/add-slot',
  path: '/add-slot',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSlotIdRoute = AuthenticatedSlotIdRouteImport.update({
  id: '/slot/$id',
  path: '/slot/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMessagesReservationIdRoute =
  AuthenticatedMessagesReservationIdRouteImport.update({
    id: '/messages/$reservationId',
    path: '/messages/$reservationId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEditSlotIdRoute = AuthenticatedEditSlotIdRouteImport.update({
  id: '/edit-slot/$id',
  path: '/edit-slot/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAvailabilityIdRoute =
  AuthenticatedAvailabilityIdRouteImport.update({
    id: '/availability/$id',
    path: '/availability/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRouteRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/add-slot': typeof AuthenticatedAddSlotRoute
  '/bookings': typeof AuthenticatedBookingsRoute
  '/earnings': typeof AuthenticatedEarningsRoute
  '/help': typeof AuthenticatedHelpRoute
  '/home': typeof AuthenticatedHomeRoute
  '/map': typeof AuthenticatedMapRoute
  '/my-slots': typeof AuthenticatedMySlotsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/reservations': typeof AuthenticatedReservationsRoute
  '/saved': typeof AuthenticatedSavedRoute
  '/vehicles': typeof AuthenticatedVehiclesRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/availability/$id': typeof AuthenticatedAvailabilityIdRoute
  '/edit-slot/$id': typeof AuthenticatedEditSlotIdRoute
  '/messages/$reservationId': typeof AuthenticatedMessagesReservationIdRoute
  '/slot/$id': typeof AuthenticatedSlotIdRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRouteRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/add-slot': typeof AuthenticatedAddSlotRoute
  '/bookings': typeof AuthenticatedBookingsRoute
  '/earnings': typeof AuthenticatedEarningsRoute
  '/help': typeof AuthenticatedHelpRoute
  '/home': typeof AuthenticatedHomeRoute
  '/map': typeof AuthenticatedMapRoute
  '/my-slots': typeof AuthenticatedMySlotsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/reservations': typeof AuthenticatedReservationsRoute
  '/saved': typeof AuthenticatedSavedRoute
  '/vehicles': typeof AuthenticatedVehiclesRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/availability/$id': typeof AuthenticatedAvailabilityIdRoute
  '/edit-slot/$id': typeof AuthenticatedEditSlotIdRoute
  '/messages/$reservationId': typeof AuthenticatedMessagesReservationIdRoute
  '/slot/$id': typeof AuthenticatedSlotIdRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/add-slot': typeof AuthenticatedAddSlotRoute
  '/_authenticated/bookings': typeof AuthenticatedBookingsRoute
  '/_authenticated/earnings': typeof AuthenticatedEarningsRoute
  '/_authenticated/help': typeof AuthenticatedHelpRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/map': typeof AuthenticatedMapRoute
  '/_authenticated/my-slots': typeof AuthenticatedMySlotsRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/reservations': typeof AuthenticatedReservationsRoute
  '/_authenticated/saved': typeof AuthenticatedSavedRoute
  '/_authenticated/vehicles': typeof AuthenticatedVehiclesRoute
  '/_authenticated/wallet': typeof AuthenticatedWalletRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/availability/$id': typeof AuthenticatedAvailabilityIdRoute
  '/_authenticated/edit-slot/$id': typeof AuthenticatedEditSlotIdRoute
  '/_authenticated/messages/$reservationId': typeof AuthenticatedMessagesReservationIdRoute
  '/_authenticated/slot/$id': typeof AuthenticatedSlotIdRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mcp'
    | '/reset-password'
    | '/admin'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/add-slot'
    | '/bookings'
    | '/earnings'
    | '/help'
    | '/home'
    | '/map'
    | '/my-slots'
    | '/notifications'
    | '/profile'
    | '/reservations'
    | '/saved'
    | '/vehicles'
    | '/wallet'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/availability/$id'
    | '/edit-slot/$id'
    | '/messages/$reservationId'
    | '/slot/$id'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mcp'
    | '/reset-password'
    | '/admin'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/add-slot'
    | '/bookings'
    | '/earnings'
    | '/help'
    | '/home'
    | '/map'
    | '/my-slots'
    | '/notifications'
    | '/profile'
    | '/reservations'
    | '/saved'
    | '/vehicles'
    | '/wallet'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/availability/$id'
    | '/edit-slot/$id'
    | '/messages/$reservationId'
    | '/slot/$id'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/mcp'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/add-slot'
    | '/_authenticated/bookings'
    | '/_authenticated/earnings'
    | '/_authenticated/help'
    | '/_authenticated/home'
    | '/_authenticated/map'
    | '/_authenticated/my-slots'
    | '/_authenticated/notifications'
    | '/_authenticated/profile'
    | '/_authenticated/reservations'
    | '/_authenticated/saved'
    | '/_authenticated/vehicles'
    | '/_authenticated/wallet'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/availability/$id'
    | '/_authenticated/edit-slot/$id'
    | '/_authenticated/messages/$reservationId'
    | '/_authenticated/slot/$id'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  McpRoute: typeof McpRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/wallet': {
      id: '/_authenticated/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AuthenticatedWalletRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vehicles': {
      id: '/_authenticated/vehicles'
      path: '/vehicles'
      fullPath: '/vehicles'
      preLoaderRoute: typeof AuthenticatedVehiclesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/saved': {
      id: '/_authenticated/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof AuthenticatedSavedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reservations': {
      id: '/_authenticated/reservations'
      path: '/reservations'
      fullPath: '/reservations'
      preLoaderRoute: typeof AuthenticatedReservationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-slots': {
      id: '/_authenticated/my-slots'
      path: '/my-slots'
      fullPath: '/my-slots'
      preLoaderRoute: typeof AuthenticatedMySlotsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/map': {
      id: '/_authenticated/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof AuthenticatedMapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help': {
      id: '/_authenticated/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AuthenticatedHelpRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/earnings': {
      id: '/_authenticated/earnings'
      path: '/earnings'
      fullPath: '/earnings'
      preLoaderRoute: typeof AuthenticatedEarningsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bookings': {
      id: '/_authenticated/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof AuthenticatedBookingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/add-slot': {
      id: '/_authenticated/add-slot'
      path: '/add-slot'
      fullPath: '/add-slot'
      preLoaderRoute: typeof AuthenticatedAddSlotRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/slot/$id': {
      id: '/_authenticated/slot/$id'
      path: '/slot/$id'
      fullPath: '/slot/$id'
      preLoaderRoute: typeof AuthenticatedSlotIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages/$reservationId': {
      id: '/_authenticated/messages/$reservationId'
      path: '/messages/$reservationId'
      fullPath: '/messages/$reservationId'
      preLoaderRoute: typeof AuthenticatedMessagesReservationIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/edit-slot/$id': {
      id: '/_authenticated/edit-slot/$id'
      path: '/edit-slot/$id'
      fullPath: '/edit-slot/$id'
      preLoaderRoute: typeof AuthenticatedEditSlotIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/availability/$id': {
      id: '/_authenticated/availability/$id'
      path: '/availability/$id'
      fullPath: '/availability/$id'
      preLoaderRoute: typeof AuthenticatedAvailabilityIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRoute
  AuthenticatedAddSlotRoute: typeof AuthenticatedAddSlotRoute
  AuthenticatedBookingsRoute: typeof AuthenticatedBookingsRoute
  AuthenticatedEarningsRoute: typeof AuthenticatedEarningsRoute
  AuthenticatedHelpRoute: typeof AuthenticatedHelpRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedMapRoute: typeof AuthenticatedMapRoute
  AuthenticatedMySlotsRoute: typeof AuthenticatedMySlotsRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedReservationsRoute: typeof AuthenticatedReservationsRoute
  AuthenticatedSavedRoute: typeof AuthenticatedSavedRoute
  AuthenticatedVehiclesRoute: typeof AuthenticatedVehiclesRoute
  AuthenticatedWalletRoute: typeof AuthenticatedWalletRoute
  AuthenticatedAvailabilityIdRoute: typeof AuthenticatedAvailabilityIdRoute
  AuthenticatedEditSlotIdRoute: typeof AuthenticatedEditSlotIdRoute
  AuthenticatedMessagesReservationIdRoute: typeof AuthenticatedMessagesReservationIdRoute
  AuthenticatedSlotIdRoute: typeof AuthenticatedSlotIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRoute,
  AuthenticatedAddSlotRoute: AuthenticatedAddSlotRoute,
  AuthenticatedBookingsRoute: AuthenticatedBookingsRoute,
  AuthenticatedEarningsRoute: AuthenticatedEarningsRoute,
  AuthenticatedHelpRoute: AuthenticatedHelpRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedMapRoute: AuthenticatedMapRoute,
  AuthenticatedMySlotsRoute: AuthenticatedMySlotsRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedReservationsRoute: AuthenticatedReservationsRoute,
  AuthenticatedSavedRoute: AuthenticatedSavedRoute,
  AuthenticatedVehiclesRoute: AuthenticatedVehiclesRoute,
  AuthenticatedWalletRoute: AuthenticatedWalletRoute,
  AuthenticatedAvailabilityIdRoute: AuthenticatedAvailabilityIdRoute,
  AuthenticatedEditSlotIdRoute: AuthenticatedEditSlotIdRoute,
  AuthenticatedMessagesReservationIdRoute:
    AuthenticatedMessagesReservationIdRoute,
  AuthenticatedSlotIdRoute: AuthenticatedSlotIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  McpRoute: McpRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
